### ISSUE TITLE
Eviction wil delete at most one pod per load exceeded

### ISSUE THREAD

**Issue by rtreffer** [mittwald/kubernetes-loadwatcher#3]
I am currently trying to adapt the loadwatcher to use the cpu pressure interface instead of load.

While doing so I noticed that the watcher will internally cache the state and only send one signal when the load is exceeded https://github.com/mittwald/kubernetes-loadwatcher/blob/master/pkg/loadwatcher/watcher_run.go#L36

The main loop forwards this to the evicter
https://github.com/mittwald/kubernetes-loadwatcher/blob/master/cmd/main.go#L86

This has multiple issues:

1. The evicter will only be called once per load exceeded event
2. A slowly increasing load (taint threshold < load < eviction threshold) will never cause an eviction until the load goes below the taint threshold and raises again.

As a result at most one eviction will happen per load exceeded event.

**Comment by martin-helmich** [comment]
Good catch. :+1: Can't believe we've missed this all this time. 🤦  Will look into this a bit more tomorrow.
